# Configuration variables are loaded by docker-compose from the .env file

# Ubuntu 16.04.3 LTS has docker-compose 1.8.0, so it doesn't support 3.x
version: "2.0"

services:
  elasticsearch:
    container_name: "${NAME}_elasticsearch"
    image: khezen/elasticsearch:6.5.4
    environment:
      - "CLUSTER_NAME=developers-italia"
      - "ELASTIC_PWD=${ELASTIC_PWD}"
      - "KIBANA_PWD=${KIBANA_PWD}"
      - "ES_TMPDIR=/tmp"
      - "HTTP_SSL=false"
      - "HTTP_CORS_ENABLE=true"
      - "HTTP_CORS_ALLOW_ORIGIN=/^https://(.+\\.)?${DOMAIN}/"
    ports:
      - "127.0.0.1:9200:9200"
    restart: always
    volumes:
      - /data/elasticsearch:/elasticsearch/data
      - ./elasticsearch/config/elasticsearch.yml:/elasticsearch/config/elasticsearch.yml
      - ./elasticsearch/config/searchguard/sg_config.yml:/elasticsearch/config/searchguard/sg_config.yml
      - ./elasticsearch/config/searchguard/sg_action_groups.yml:/elasticsearch/config/searchguard/sg_action_groups.yml
      - ./elasticsearch/config/searchguard/sg_internal_users.yml:/elasticsearch/config/searchguard/sg_internal_users.yml
      - ./elasticsearch/config/searchguard/sg_roles.yml:/elasticsearch/config/searchguard/sg_roles.yml
      - ./elasticsearch/config/searchguard/sg_roles_mapping.yml:/elasticsearch/config/searchguard/sg_roles_mapping.yml

  # kibana:
  #   container_name: "${NAME}_kibana"
  #   image: khezen/kibana:6.2.2
  #   environment:
  #     - "ELASTICSEARCH_PROTOCOL=http"
  #     - "ELASTICSEARCH_HOST=elasticsearch"
  #     - "ELASTICSEARCH_PORT=9200"
  #     - "KIBANA_PWD=${KIBANA_PWD}"
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=kibana"
  #     - "traefik.port=5601"
  #     - "traefik.frontend.rule=Host:kibana.${DOMAIN}"
  #   restart: always
  #   volumes:
  #     - ./kibana/config/kibana.yml:/opt/kibana-6.2.2-linux-x86_64/config/kibana.yml

  # prometheus:
  #   container_name: "${NAME}_prometheus"
  #   image: quay.io/prometheus/prometheus:v2.2.1
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.backend=prometheus"
  #     - "traefik.port=9090"
  #     - "traefik.frontend.rule=Host:prometheus.${DOMAIN}"
  #   restart: always
  #   volumes:
  #     - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

# SPC Cloud machines have MTU 1400, and docker-compose does not automatically pick
# the host daemon MTU.
# https://github.com/moby/moby/issues/22297
# https://github.com/docker/compose/issues/3438
networks:
  default:
    driver_opts:
      com.docker.network.driver.mtu: 1400
