admin:
  cluster:
    - ALL
  indices:
    "*":
      "*":
        - ALL

kibana_user:
  cluster:
    - MONITOR
    - CRUD
  indices:
    '?kibana':
      '*':
        - INDEX_ALL
        - READ

search:
  indices:
    'publiccode_*':
      '*':
        - SEARCH
    'jekyll_*':
      '*':
        - SEARCH
