admin:
  cluster:
    - ALL
  indices:
    "*":
      "*":
        - ALL

kibana_user:
  cluster:
    - MONITOR
    - CRUD
  indices:
    '?kibana':
      '*':
        - INDEX_ALL
        - READ

search:
  indices:
    # jekyll is the alias that includes all the indices we need to query
    'jekyll':
      '*':
        - SEARCH
    'indicepa':
      '*':
        - SEARCH

